CREATE DATABASE ASSIGNMENT;
USE ASSIGNMENT ;

CREATE TABLE FULL_STACK_WITH_PHP(ID INT NOT NULL, SNAME VARCHAR(255) NOT NULL, AGE INT NOT NULL, GENDER VARCHAR(10) NOT NULL,
                  SLEVEL VARCHAR(25) NOT NULL, PHONENUMBER VARCHAR(45) NOT NULL, YOS VARCHAR(45) NOT NULL, LOCATION VARCHAR(255) NOT NULL);